slickapp/urls.py
from django.urls import path
from .views import *

app_name = 'slickapp'

urlpatterns = [

    # TemplateView
    path('', home.as_view(), name="home"),
    path('about', about_us.as_view(), name="abut_us"),
    path('services', services.as_view(), name="services"),
    path('contact-us', contactus.as_view(), name="contactus"),
    path('project-management', ProjectManagementView.as_view(), name="project_management_view"),
    path('mobile-development', MobileDevelopmentView.as_view(), name="mobile_development_view"),
    path('custom-web-development', CustomWebView.as_view(), name="custom_web_view"),
    path('panel-web-development', PanelWebDevelopmentView.as_view(), name="panel_web_view"),
    path('digital-marketing', DigitalMarketingView.as_view(), name="digital_marketing_view"),
    path('community-recruitment', CommunityRecruitmentView.as_view(), name="community_recruitment_view"),
    path('terms-conditions', Terms_conditionsview.as_view(), name="terms_conditions_view"),
    path('privacy-policy', Privacy_policyview.as_view(), name="privacy_policy_view"),
    

]

slickwebsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('slickapp.urls'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Slick | IT (Software) Company Landing</title>
  <meta name="description"
    content="Unleash the power of the digital world with our expert web development services. Our  professed  platoon combines  slice- edge technologies with creative design to  make stunning websites that allure and engage your  followership. From responsive layouts to  flawless  stoner  gests , we deliver  acclimatized  results that elevate your online presence. Discover the perfect  mix of  invention and functionality, backed by our  unvarying commitment to quality and  customer satisfaction. transfigure your vision into reality with our trusted web development  mate.">
  <meta name="keywords"
    content="Market Research Website Development, SEO-Friendly Market Research Website, Web Development Services,Responsive Web Development,E-Commerce Website Development, UI/UX Design and Development, Project Management Tool, Market Research Project Management Software, Mobile App Development">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="google-site-verification" content="ORp-fJxVBAxWqEI_dYiYeYo-5l3ekFeLQUoBrMDls34" />
  <meta name="p:domain_verify" content="77ec98f900f344c298960fa535f2e321" />

  <!-- Viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Favicon and Touch Icons -->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/favicon/logo_180.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/favicon/logo_32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/favicon/logo_16.png' %}">
  <link rel="manifest" href="{% static 'assets/favicon/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'assets/favicon/safari-pinned-tab.svg' %}" color="#6366f1">
  <link rel="shortcut icon" href="{% static 'assets/favicon/slick.ico' %}">
  <meta name="msapplication-TileColor" content="#080032">
  <meta name="msapplication-config" content="{% static 'assets/favicon/browserconfig.xml'%}">
  <meta name="theme-color" content="#ffffff">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

  <!-- Vendor Styles -->
  <link rel="stylesheet" media="screen" href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" />
  <link rel="stylesheet" media="screen" href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" />
  <link rel="stylesheet" media="screen" href="{% static 'assets/vendor/img-comparison-slider/dist/styles.css' %}" />
  <link rel="stylesheet" media="screen"
    href="{% static 'assets/vendor/lightgallery/css/lightgallery-bundle.min.css' %}" />

  <!-- Main Theme Styles + Bootstrap -->
  <link rel="stylesheet" media="screen" href="{% static 'assets/css/theme.min.css' %}">
  <link rel="stylesheet" media="screen" href="{% static 'assets/css/style.css' %}">
  <link rel="stylesheet" href="assets/css/Navbar-Right-Links-icons.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/css/Navbar-Centered-Links-icons.css">

  <!-- Page loading styles -->
  <style>
    .page-loading {
      position: fixed;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      width: 100%;
      height: 100%;
      -webkit-transition: all .4s .2s ease-in-out;
      transition: all .4s .2s ease-in-out;
      background-color: #fff;
      opacity: 0;
      visibility: hidden;
      z-index: 9999;
    }

    .dark-mode .page-loading {
      background-color: #0b0f19;
    }

    .page-loading.active {
      opacity: 1;
      visibility: visible;
    }

    .page-loading-inner {
      position: absolute;
      top: 50%;
      left: 0;
      width: 100%;
      text-align: center;
      -webkit-transform: translateY(-50%);
      transform: translateY(-50%);
      -webkit-transition: opacity .2s ease-in-out;
      transition: opacity .2s ease-in-out;
      opacity: 0;
    }

    .page-loading.active>.page-loading-inner {
      opacity: 1;
    }

    .page-loading-inner>span {
      display: block;
      font-size: 1rem;
      font-weight: normal;
      color: #9397ad;
    }

    .dark-mode .page-loading-inner>span {
      color: #fff;
      opacity: .6;
    }

    .page-spinner {
      display: inline-block;
      width: 2.75rem;
      height: 2.75rem;
      margin-bottom: .75rem;
      vertical-align: text-bottom;
      border: .15em solid #b4b7c9;
      border-right-color: transparent;
      border-radius: 50%;
      -webkit-animation: spinner .75s linear infinite;
      animation: spinner .75s linear infinite;
    }

    .dark-mode .page-spinner {
      border-color: rgba(255, 255, 255, .4);
      border-right-color: transparent;
    }

    @-webkit-keyframes spinner {
      100% {
        -webkit-transform: rotate(360deg);
        transform: rotate(360deg);
      }
    }

    @keyframes spinner {
      100% {
        -webkit-transform: rotate(360deg);
        transform: rotate(360deg);
      }
    }
  </style>

  <!-- Theme mode -->
  <script>
    let mode = window.localStorage.getItem('mode'),
      root = document.getElementsByTagName('html')[0];
    if (mode !== null && mode === 'dark') {
      root.classList.add('dark-mode');
    } else {
      root.classList.remove('dark-mode');
    }
  </script>

  <!-- Page loading scripts -->
  <script>
    (function () {
      window.onload = function () {
        const preloader = document.querySelector('.page-loading');
        preloader.classList.remove('active');
        setTimeout(function () {
          preloader.remove();
        }, 1000);
      };
    })();
  </script>

  <script async src="https://www.googletagmanager.com/gtag/js?id=G-9VSBNEQWXS"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', 'G-9VSBNEQWXS');
  </script>
</head>


<!-- Body -->

<body>

  <!-- Page loading spinner -->
  <div class="page-loading active">
    <div class="page-loading-inner">
      <div class="page-spinner"></div><span>Loading...</span>
    </div>
  </div>

  <main class="page-wrapper">
    <nav class="navbar navbar-expand-md bg-body py-3 sticky-top">
      <div class="container"><a class="navbar-brand d-flex align-items-center" href="{%url 'slickapp:home'%}"><img src="{% static 'assets/img/slick_logo_1.png' %}" width="120" alt="Silicon"></a>
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2">
          <span class="visually-hidden">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-2">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item"><a class="nav-link {{home}}" href="{%url 'slickapp:home'%}">Home</a></li>
            <li class="nav-item"><a class="nav-link {{about_us}}" href="{%url 'slickapp:abut_us'%}">About Us</a></li>
            <li class="nav-item"><a class="nav-link {{services}}" href="{%url 'slickapp:services'%}">Services</a></li>
            <li class="nav-item"><a class="nav-link {{contactus}}" href="{% url 'slickapp:contactus'%}">Contact</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </main>

    {% block content %}

    {% endblock %}


    <!-- Footer -->
    <footer class="footer dark-mode bg-dark pt-5 pb-4 pb-lg-5">
      <div class="container pt-lg-4">
        <div class="row pb-5">
          <div class="col-lg-4 col-md-6">
            <div class="navbar-brand text-dark p-0 me-0 mb-3 mb-lg-4">
              <img src="{% static 'assets/img/slick_logo_white.png' %}" width="120" alt="Slick">
            </div>
            <p class="fs-sm text-light opacity-70 pb-lg-3 mb-4">Our creativity is your start of successful projects!.
            </p>
            <form class="needs-validation" novalidate>
              <label for="subscr-email" class="form-label">Subscribe to our newsletter</label>
            </form>
          </div>
          <div class="col-xl-6 col-lg-7 col-md-5 offset-xl-2 offset-md-1 pt-4 pt-md-1 pt-lg-0">
            <div id="footer-links" class="row">
              <div class="col-lg-4">
                <h6 class="mb-2">
                  <a href="#useful-links" class="d-block text-dark dropdown-toggle d-lg-none py-2"
                    data-bs-toggle="collapse">Useful Links</a>
                </h6>
                <div id="useful-links" class="collapse d-lg-block" data-bs-parent="#footer-links">
                  <ul class="nav flex-column pb-lg-1 mb-lg-3">
                    <li class="nav-item"><a href="{%url 'slickapp:home'%}"
                        class="nav-link d-inline-block px-0 pt-1 pb-2">Home</a></li>
                    <li class="nav-item"><a href="{%url 'slickapp:abut_us'%}"
                        class="nav-link d-inline-block px-0 pt-1 pb-2">About Us</a></li>
                    <li class="nav-item"><a href="{%url 'slickapp:services'%}"
                        class="nav-link d-inline-block px-0 pt-1 pb-2">Services</a></li>
                    <li class="nav-item"><a href="{%url 'slickapp:contactus'%}"
                        class="nav-link d-inline-block px-0 pt-1 pb-2">Contact Us</a></li>
                  </ul>
                  <ul class="nav flex-column mb-2 mb-lg-0">
                    <li class="nav-item"><a href="{%url 'slickapp:terms_conditions_view'%}" target="blank" class="nav-link d-inline-block px-0 pt-1 pb-2">Terms &amp;
                        Conditions</a></li>
                    <li class="nav-item"><a href="{%url 'slickapp:privacy_policy_view'%}" target="blank" class="nav-link d-inline-block px-0 pt-1 pb-2">Privacy Policy</a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-xl-4 col-lg-3">
                <h6 class="mb-2">
                  <a href="#social-links" class="d-block text-dark dropdown-toggle d-lg-none py-2"
                    data-bs-toggle="collapse">Socials</a>
                </h6>
                <div id="social-links" class="collapse d-lg-block" data-bs-parent="#footer-links">
                  <ul class="nav flex-column mb-2 mb-lg-0">
                    <li class="nav-item"><a href="https://www.facebook.com/slickservice/" target="blank"
                        class="nav-link d-inline-block px-0 pt-1 pb-2">Facebook</a></li>
                    <li class="nav-item"><a href="https://www.linkedin.com/company/slick-services/" target="blank"
                        class="nav-link d-inline-block px-0 pt-1 pb-2">LinkedIn</a></li>
                    <li class="nav-item"><a href="https://twitter.com/i/flow/login" target="blank"
                        class="nav-link d-inline-block px-0 pt-1 pb-2">Twitter</a></li>
                    <li class="nav-item"><a href="https://www.instagram.com/accounts/login/" target="blank"
                        class="nav-link d-inline-block px-0 pt-1 pb-2">Instagram</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-xl-4 col-lg-5 pt-2 pt-lg-0">
                <h6 class="mb-2">Contact Us</h6>
                <a class="fw-medium" href="{%url 'slickapp:contactus'%}">sales@slickservices.in</a>
              </div>
            </div>
          </div>
        </div>
        <p class="nav d-block fs-xs text-center text-md-start pb-2 pb-lg-0 mb-0">
          <span class="text-light opacity-50">&copy; Copy right all rights reserved.</span>
          <a class="nav-link d-inline-block p-0" rel="noopener">Slick Services</a>
        </p>
      </div>
    </footer>


    <!-- Back to top button -->
    <a href="#top" class="btn-scroll-top" data-scroll>
      <span class="btn-scroll-top-tooltip text-muted fs-sm me-2">Top</span>
      <i class="btn-scroll-top-icon bx bx-chevron-up"></i>
    </a>


    <!-- Vendor Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"></script>
    <script src="{% static 'assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
    <script src="{% static 'assets/vendor/vanilla-tilt/dist/vanilla-tilt.min.js' %}"></script>
    <script src="{% static 'assets/vendor/parallax-js/dist/parallax.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jarallax/dist/jarallax.min.js' %}"></script>
    <script src="{% static 'assets/vendor/rellax/rellax.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/img-comparison-slider/dist/index.js' %}"></script>
    <script src="{% static 'assets/vendor/@lottiefiles/lottie-player/dist/lottie-player.js' %}"></script>
    <script src="{% static 'assets/vendor/cleave.js/dist/cleave.min.js' %}"></script>
    <script src="{% static 'assets/vendor/lightgallery/lightgallery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/lightgallery/plugins/fullscreen/lg-fullscreen.min.js' %}"></script>
    <script src="{% static 'assets/vendor/lightgallery/plugins/zoom/lg-zoom.min.js' %}"></script>
    <script src="{% static 'assets/vendor/lightgallery/plugins/video/lg-video.min.js' %}"></script>


    <!-- Main Theme Script -->
    <script src="{% static 'assets/js/theme.min.js' %}"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>

</body>

</html>

templates/contacts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}contact-us{% endblock %}
{% block content %}


      <!-- Page content -->
      <section class="bg-size-cover bg-position-bottom-center bg-repeat-0 py-5" style="background-image: url(assets/img/contacts/bg.svg);">
        <div class="container pt-5 pb-lg-4 pb-xl-5">

          <!-- Breadcrumb -->
          <nav class="pt-lg-4" aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
              <li class="breadcrumb-item">
                <a><i class="bx bx-home-alt fs-lg me-1"></i>Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">Contacts</li>
            </ol>
          </nav>

          <div class="row pt-md-2 pt-lg-5 pb-2 pb-md-4">
            <div class="col-xxl-4 col-xl-5 col-lg-6 pt-3 mt-3">
              <h2 class="pb-sm-2 pb-md-3 mb-3">Want to work with us?</h>
              <h2 class="display-1 text-gradient-primary pb-sm-2 pb-md-3 mb-3">Let's talk!</h2>
              <!-- fw-normal pb-2 mb-4 -->
              <div class="contact-details"><a class="nav-link mb-2 text-primary"><i class='bx bx-envelope bx-md'></i> sales@slickservices.in</a></div>
              <div class="nav-link mb-3 text-primary"><i class='bx bxs-phone-call bx-md' ></i> +91 9009989797</div>
              <div class="nav-link mb-3 text-primary"><i class='bx bx-location-plus bx-md'></i> 404 , Central Sangath IPL, behind 4D Square Mall, near North Plaza, Motera, Ahmedabad, Gujarat, India - 380005 </div>
              
            </div>
            <div class="col-lg-6 offset-xl-1 offset-xxl-2 pt-3 pt-md-4 pt-lg-3 mt-3">
              <form class="needs-validation" novalidate action="{% url 'slickapp:contactus' %}"  method="post">
                {% csrf_token %}
                {% for message in messages %}
                <div class="alert {{message.tags}} fade show text-left" role="alert">
                    {{message}}
                </div>
                {% endfor %}
                <div class="row g-4">
                  <div class="col-sm-6">
                    <label for="fn" class="form-label fs-base">Full name</label>
                    <input type="text" class="form-control form-control-lg" id="fn" name="full_name" required>
                    <div class="invalid-feedback">Please enter your full name!</div>
                  </div>
                  <div class="col-sm-6">
                    <label for="email" class="form-label fs-base">Email</label>
                    <input type="email" class="form-control form-control-lg" id="email" name="email" required>
                    <div class="invalid-feedback">Please provide a valid email address!</div>
                  </div>
                  <div class="col-sm-12">
                    <label for="services" class="form-label fs-base">Topic</label>
                    <select class="form-control form-control-lg" id="services" name="services" required>
                      <option selected disabled>Select Topic</option>
                      {% for visitor_query_obj_list_key, visitor_query_obj_list_value in visitor_query_obj.items%}
                        <option value="{{visitor_query_obj_list_key}}">{{visitor_query_obj_list_value}}</option>
                      {% endfor %}
                    </select>
                    <div class="invalid-feedback">Please provide a Subject</div>
                  </div>
                  <div class="col-12 pb-2">
                    <label for="message" class="form-label fs-base">Message</label>
                    <textarea class="form-control form-control-lg" id="message" rows="3" name="message" required></textarea>
                    <div class="invalid-feedback">Please provide a valid email address!</div>
                  </div>
                  <div class="col-12">
                    <button type="submit" class="btn btn-lg btn-primary w-100 w-sm-auto">Contact Us</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
    


    {% endblock %}

templates/privacy_policy.html
{% extends 'base.html' %}
{% load static %}
{% block title %}FAQ{% endblock %}
{% block content %}



    <div class="container">
        <div style="text-align: center;">
            <h1><br>Privacy Policy for SLICK SERVICES</h1>
        </div>
        <div style="text-align: justify;">
            <p style="text-align: justify;"><br>Last Updated: 7/18/2023<br><br>At Slick Services, we take the privacy and security of our users' personal information seriously. This Privacy Policy outlines how we collect, use, store, and protect the data provided to us through our website and any related services. By accessing and using our website, you agree to the terms of this Privacy Policy. If you do not agree with these terms, please do not use our services</p>
            <h6><strong>1. Information We Collect:</strong></h6>
            <p> <strong>a. Personal Information:</strong> We may collect personal information, such as your name, email address, phone number, and other contact details when you voluntarily submit it to us through our website or other communication channels.</p>
            <p> <strong>b. Usage Data:</strong> We may collect non-personal information related to your use of our website, such as your IP address, browser type, operating system, and website pages visited. This information is collected through cookies and similar tracking technologies.</p>
            <h6><strong>2. How We Use Your Information:</strong></h6>
            <p> <strong>a. To Provide Services:</strong> We use the personal information you provide to respond to inquiries, fulfil service requests, and provide support and assistance related to our web development services.</p>
            <p> <strong>b. To Improve User Experience:</strong> Usage data helps us understand how visitors interact with our website, allowing us to optimize its design, content, and functionality to enhance user experience.</p>
            <p> <strong>c. To Send Updates:</strong> With your consent, we may send you periodic newsletters, updates, and promotional materials related to our services. You can opt-out of receiving these communications at any time.</p>
            <h6><strong>3. Data Sharing and Security:</strong></h6>
            <p> <strong>a. Third-Party Service Providers:</strong> We may share your information with trusted third-party service providers who assist us in delivering our services, such as hosting providers or analytics tools. These parties are bound by confidentiality agreements and are not allowed to use your data for any other purpose.</p>
            <p> <strong>b. Legal Compliance:</strong> We may disclose personal information when required by law or in response to valid legal requests.</p>
            <p> <strong>c. Data Security:</strong> We implement industry-standard security measures to protect your personal information from unauthorized access, loss, misuse, or alteration. However, no method of transmission over the internet or electronic storage is entirely secure, and we cannot guarantee absolute security.</p>
            <h6><strong>4. Third-Party Links:</strong></h6>
            <p>Our website may contain links to third-party websites. Please note that we are not responsible for the privacy practices of these websites. We encourage you to review their privacy policies when visiting their sites.</p>
            <h6><strong>5. Children's Privacy:</strong></h6>
            <p>Our services are not intended for individuals under the age of 16. We do not knowingly collect personal information from children. If you believe we have inadvertently collected information from a child, please contact us immediately, and we will take appropriate steps to delete the data.</p>
            <h6><strong>6. Changes to the Privacy Policy:</strong></h6>
            <p>We may update this Privacy Policy from time to time to reflect changes in our practices or for legal or regulatory reasons. We will notify you of any significant changes by posting the updated policy on our website or through other communication methods.</p>
            <h6><strong>7. Contact Us:</strong></h6>
            <p>If you have any questions, concerns, or requests related to this Privacy Policy or your personal information, please contact us at:</p>
            <p>SLICK SERVICES</p>
            <p><strong>📧 Email: <a href="mailto:info@slickservices.in">info@slickservices.in /</a></strong></p>
            <p>☎️ Phone: +91 90099 89797</p>
            <p>Thank you for choosing Slick Services. We value your trust and are committed to safeguarding your privacy.</p>
        </div>
    </div>
    
    {% endblock %}

templates/terms_conditions.html
{% extends 'base.html' %}
{% load static %}
{% block title %}FAQ{% endblock %}
{% block content %}
 
    <div class="container">
        <div style="text-align: center;">
            <h1><br>Terms and Conditions for SLICK SERVICES</h1>
        </div>
        <div style="text-align: justify;">
            <p><br>Last Updated: 7/18/2023<br><br>Please read these Terms and Conditions ("Terms") carefully before using the services provided by Slick Services. By accessing or using our web development services, you agree to be bound by these Terms. If you do not agree with these Terms, please refrain from using our services.<br><br></p>
            <h6><strong>1. Scope of Services:</strong></h6>
            <p>a. Slick Services offers web development and related services to clients worldwide. We specialize in creating custom websites, web applications, and e-commerce solutions.</p>
            <p>b. Our services are provided on an "as-is" and "as-available" basis. While we strive to ensure the accuracy and functionality of our deliverables, we do not guarantee that they will be error-free or meet all of your requirements.</p>
            <h6><strong>2. Client Responsibilities:</strong></h6>
            <p>a. To utilize our services, you must provide accurate and complete information during the project initiation and development process. Any delays or inaccuracies in providing required information may affect project timelines.</p>
            <p>b. You are responsible for the content and materials (text, images, media, etc.) that will be integrated into the web development project. You must ensure that you have the necessary rights to use such content, and it does not violate any copyright or intellectual property laws.</p>
            <p>c. You agree to cooperate with Slick Services during the development process and provide timely feedback and approvals when required.</p>
            <h6><strong>3. Payment and Fees:</strong></h6>
            <p>a. Payment terms will be agreed upon before the project commences. You agree to make timely payments according to the agreed schedule.</p>
            <p>b. Slick Services reserves the right to suspend or terminate services if payments are not made as per the agreed terms.</p>
            <h6><strong>4. Intellectual Property:</strong></h6>
            <p>a. Any intellectual property, including but not limited to code, designs, and graphics, created by Slick Services during the project will remain the property of Slick Services until full payment is received.</p>
            <p>b. Upon receiving full payment, Slick Services grants you a non-exclusive, non-transferable license to use the completed project solely for your business purposes.</p>
            <h6><strong>5. Confidentiality:</strong></h6>
            <p>a. Both parties agree to treat any confidential information disclosed during the project as strictly confidential. This includes project details, pricing, business strategies, and other sensitive information.</p>
            <p>b. Upon receiving full payment, Slick Services grants you a non-exclusive, non-transferable license to use the completed project solely for your business purposes.</p>
            <h6><strong>6. Termination:</strong></h6>
            <p>a. Either party may terminate the project for cause if the other party materially breaches these Terms and fails to remedy the breach within a reasonable timeframe.</p>
            <p>b. If you terminate the project before completion, you agree to pay for the services rendered up to the termination date.</p>
            <h6><strong>7. Limitation of Liability:</strong></h6>
            <p>a. Slick Services will not be liable for any indirect, consequential, or incidental damages arising from the use of our services or the completed project.</p>
            <p>b. In no event shall Slick Service's liability exceed the total fees paid for the specific project.</p>
            <h6><strong>8. Governing Law:</strong></h6>
            <p>These Terms shall be governed by and construed in accordance with the laws of Slick Services, without regard to conflicts of law principles.</p>
            <h6><strong>9. Modification of Terms:</strong></h6>
            <p>Slick Services reserves the right to modify or update these Terms at any time without prior notice. It is your responsibility to review these Terms periodically for changes.</p>
            <h6><strong>10. Contact Us:</strong></h6>
            <p>If you have any questions or concerns about these Terms or our services, please contact us at:</p>
            <p>SLICK SERVICES</p>
            <p>📧 Email: <a href="mailto:info@slickservices.in">info@slickservices.in </a></p>
            <p>☎️ Phone: +91 90099 89797</p>
            <p>Thank you for choosing Slick Services. We look forward to delivering exceptional web development solutions tailored to your needs.</p>
         </div>    
    </div>
    
{% endblock %}